#瑞术签章配置
#授权服务器地址
#rs.pdf.authUrl=http://114.115.172.176:8080/AuthorizationCode/authorization
#授权业务id
#rs.pdf.sysId=270ee980476111e8ab32005056a72395
#unit
#rs.pdf.unit=FJRS

#凯特配置
#是否启用凯特签章 0 不启用 1 启用
kind_enable=1
#凯特签章服务器地址
#kind_url=http://www.kinsec.com:5000
#kind_url=http://192.168.1.117:1008
#凯特PDF临时文件读取类
kind_file_class_name=com.yaoan.module.econtract.service.sign.KinsecSiguature
rs.pdf.auth.enable = 0
#金格签章服务器地址 26.137:ca2介质章服务器（扫码签也属于此）  172.176:ca3云章服务器
#url=http://114.116.26.137:8089/iSignatureServer/OfficeServer.jsp
#url=http://114.115.172.176:8089/iSignatureServer/OfficeServer.jsp
#url=http://192.168.1.102:8089/iSignatureServer/OfficeServer.jsp

#是否验证服务端密码，服务器端获取印章数字签名，设置为true
verifyPwd=
#PDF文件输入输出流com.kinggrid.pdfviewer.PdfFileResource的继承类
fileClassName=com.yaoan.module.econtract.service.sign.KingGridFileResourceV2
#是否启用操作同一文档的并发限制
enableConcurrencyLimit=false
#跨域访问题
#使用com.kinggrid.pdfviewer.MyFilter过滤器设置允许跨域访问的URL地址
#建议集成产品实现跨域请求过滤
#多个逗号分开
cross.domain.urls=
#域签名时，临时文件目录，如果文件夹不存在，默认使用user.dir目录,
#原因：没有临时文件目录，临时文件将放在内存内
user.tmp=
#电子签章  PDF内容摘要算法
#实现com.kinggrid.pdf.executes.electronicseal.KGMessageDigest接口
messageDigest=
#第三方数字签名
#实现com.kinggrid.pdfviewer.pdf.ThridPartySig
thridPartySig=
#验证数字签名，加密机/签名验签服务器等，签章服务也可以对接，【单实例】
#实现com.kinggrid.pdfviewer.pdf.electronicseal.VerifyDigitalSignature接口
verifyDigitalSignature=com.reach.pdf.sign.base.verify.ReachVerify
#OFD转PDF云转换服务器地址。
docs.url=
#运营平台服务器地址
yypt.url=
#应用唯一标识，在应用管理中获取
appKey=
#盐值
appSalt=
#国办印章软验证时，对接签章服务器验证印章的有效性
checkSealStats=false

#接口服务器地址
rs.pdf.interfaceUrl=

#文档处理服务器地址
rs.pdf.docProcessUrl=
#
rs.pdf.demourl=


rs.pdf.authUrl=http://openapi.rsigncloud.com:7300/AuthorizationCode/authorization
rs.pdf.sysId=af004e9edac611e9a4b800163e12f319
rs.pdf.unit=FJBS
kind_url=http://kf.fjdzyz.com:5000

#url=http://esealplus.rsigncloud.com:8089/iSignatureServer/OfficeServer.jsp
url=http://testesealplus.rsigncloud.com:8089/iSignatureServer/OfficeServer.jsp 


yhPdfClassName=com.yaoan.module.econtract.service.sign.yhPdfResource
yhOfdClassName=com.yaoan.module.econtract.service.sign.YhOfdResource