tokenUrl=http://10.5.53.56:7002/gp-auth-center/oauth/token
clientId=yndzht-client
clientSecret=yndzht-secret
grantType=password
username=yaoanuser
password=yaoanP@ssw0rd
sendUrl=http://10.5.53.56:7011/gp-message-center/rest/v1/message/sendBatchMessage
businessCode=yaoantest
msgType=7