package com.yaoan.module.econtract.service.contract.com.cxf.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.7
 * 2024-03-21T10:17:35.904+08:00
 * Generated source version: 3.5.7
 *
 */
@WebServiceClient(name = "LawyeeServiceService",
                  wsdlLocation = "http://218.247.254.201:8070/cxf/services/lawyeeservice?wsdl",
                  targetNamespace = "http://tempuri.org/")
public class LawyeeServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "LawyeeServiceService");
    public final static QName LawyeeServicePort = new QName("http://tempuri.org/", "LawyeeServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://218.247.254.201:8070/cxf/services/lawyeeservice?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(LawyeeServiceService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://218.247.254.201:8070/cxf/services/lawyeeservice?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public LawyeeServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public LawyeeServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LawyeeServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public LawyeeServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public LawyeeServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public LawyeeServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns LawyeeService
     */
    @WebEndpoint(name = "LawyeeServicePort")
    public LawyeeService getLawyeeServicePort() {
        return super.getPort(LawyeeServicePort, LawyeeService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LawyeeService
     */
    @WebEndpoint(name = "LawyeeServicePort")
    public LawyeeService getLawyeeServicePort(WebServiceFeature... features) {
        return super.getPort(LawyeeServicePort, LawyeeService.class, features);
    }

}
