package com.yaoan.module.econtract.service.contract.com.cxf.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.7
 * 2024-03-21T10:17:35.873+08:00
 * Generated source version: 3.5.7
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "LawyeeService")
@XmlSeeAlso({ObjectFactory.class})
public interface LawyeeService {

    @WebMethod(operationName = "CheckManyFileCallBackToken", action = "http://tempuri.org/CheckManyFileCallBackToken")
    @RequestWrapper(localName = "CheckManyFileCallBackToken", targetNamespace = "http://tempuri.org/", className = "com.cxf.client.CheckManyFileCallBackToken")
    @ResponseWrapper(localName = "CheckManyFileCallBackTokenResponse", targetNamespace = "http://tempuri.org/", className = "com.cxf.client.CheckManyFileCallBackTokenResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String checkManyFileCallBackToken(

        @WebParam(name = "DocumentInfos", targetNamespace = "http://tempuri.org/")
        java.lang.String documentInfos,
        @WebParam(name = "Token", targetNamespace = "http://tempuri.org/")
        java.lang.String token
    );

    @WebMethod(operationName = "SaveFile")
    @RequestWrapper(localName = "SaveFile", targetNamespace = "http://tempuri.org/", className = "com.cxf.client.SaveFile")
    @ResponseWrapper(localName = "SaveFileResponse", targetNamespace = "http://tempuri.org/", className = "com.cxf.client.SaveFileResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String saveFile(

        @WebParam(name = "CaseID", targetNamespace = "http://tempuri.org/")
        java.lang.String caseID,
        @WebParam(name = "DocumentData", targetNamespace = "http://tempuri.org/")
        byte[] documentData,
        @WebParam(name = "Sign", targetNamespace = "http://tempuri.org/")
        java.lang.String sign
    );

    @WebMethod(operationName = "DocSensitiveCheck", action = "http://tempuri.org/DocSensitiveCheck")
    @RequestWrapper(localName = "DocSensitiveCheck", targetNamespace = "http://tempuri.org/", className = "com.cxf.client.DocSensitiveCheck")
    @ResponseWrapper(localName = "DocSensitiveCheckResponse", targetNamespace = "http://tempuri.org/", className = "com.cxf.client.DocSensitiveCheckResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String docSensitiveCheck(

        @WebParam(name = "proxyId", targetNamespace = "http://tempuri.org/")
        java.lang.String proxyId,
        @WebParam(name = "courtid", targetNamespace = "http://tempuri.org/")
        java.lang.String courtid,
        @WebParam(name = "courtname", targetNamespace = "http://tempuri.org/")
        java.lang.String courtname,
        @WebParam(name = "userid", targetNamespace = "http://tempuri.org/")
        java.lang.String userid,
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        java.lang.String username,
        @WebParam(name = "docdata", targetNamespace = "http://tempuri.org/")
        java.lang.String docdata,
        @WebParam(name = "callBackService", targetNamespace = "http://tempuri.org/")
        java.lang.String callBackService,
        @WebParam(name = "className", targetNamespace = "http://tempuri.org/")
        java.lang.String className,
        @WebParam(name = "sign", targetNamespace = "http://tempuri.org/")
        java.lang.String sign
    );

    @WebMethod(operationName = "UpdateDocStatusOffLine")
    @RequestWrapper(localName = "UpdateDocStatusOffLine", targetNamespace = "http://tempuri.org/", className = "com.cxf.client.UpdateDocStatusOffLine")
    @ResponseWrapper(localName = "UpdateDocStatusOffLineResponse", targetNamespace = "http://tempuri.org/", className = "com.cxf.client.UpdateDocStatusOffLineResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean updateDocStatusOffLine(

        @WebParam(name = "caseid", targetNamespace = "http://tempuri.org/")
        java.lang.String caseid,
        @WebParam(name = "strReturnReason", targetNamespace = "http://tempuri.org/")
        java.lang.String strReturnReason
    );

    @WebMethod(operationName = "ImportDataExt")
    @RequestWrapper(localName = "ImportDataExt", targetNamespace = "http://tempuri.org/", className = "com.cxf.client.ImportDataExt")
    @ResponseWrapper(localName = "ImportDataExtResponse", targetNamespace = "http://tempuri.org/", className = "com.cxf.client.ImportDataExtResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String importDataExt(

        @WebParam(name = "key", targetNamespace = "http://tempuri.org/")
        java.lang.String key,
        @WebParam(name = "data", targetNamespace = "http://tempuri.org/")
        byte[] data,
        @WebParam(name = "type", targetNamespace = "http://tempuri.org/")
        java.lang.String type,
        @WebParam(name = "callBackService", targetNamespace = "http://tempuri.org/")
        java.lang.String callBackService,
        @WebParam(name = "callBackPage", targetNamespace = "http://tempuri.org/")
        java.lang.String callBackPage,
        @WebParam(name = "sign", targetNamespace = "http://tempuri.org/")
        java.lang.String sign,
        @WebParam(name = "xml", targetNamespace = "http://tempuri.org/")
        java.lang.String xml
    );

    @WebMethod(operationName = "SaveFileTest")
    @RequestWrapper(localName = "SaveFileTest", targetNamespace = "http://tempuri.org/", className = "com.cxf.client.SaveFileTest")
    @ResponseWrapper(localName = "SaveFileTestResponse", targetNamespace = "http://tempuri.org/", className = "com.cxf.client.SaveFileTestResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String saveFileTest(

        @WebParam(name = "CaseID", targetNamespace = "http://tempuri.org/")
        java.lang.String caseID,
        @WebParam(name = "DocumentData", targetNamespace = "http://tempuri.org/")
        byte[] documentData,
        @WebParam(name = "Sign", targetNamespace = "http://tempuri.org/")
        java.lang.String sign
    );

    @WebMethod(operationName = "CheckFileForOnInternet", action = "http://tempuri.org/CheckFileForOnInternet")
    @RequestWrapper(localName = "CheckFileForOnInternet", targetNamespace = "http://tempuri.org/", className = "com.cxf.client.CheckFileForOnInternet")
    @ResponseWrapper(localName = "CheckFileForOnInternetResponse", targetNamespace = "http://tempuri.org/", className = "com.cxf.client.CheckFileForOnInternetResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String checkFileForOnInternet(

        @WebParam(name = "CaseID", targetNamespace = "http://tempuri.org/")
        java.lang.String caseID,
        @WebParam(name = "DocumentData", targetNamespace = "http://tempuri.org/")
        byte[] documentData,
        @WebParam(name = "StaffCode", targetNamespace = "http://tempuri.org/")
        java.lang.String staffCode,
        @WebParam(name = "RoleId", targetNamespace = "http://tempuri.org/")
        java.lang.String roleId
    );

    @WebMethod(operationName = "LawyeeCenterUpdateDocStatus")
    @RequestWrapper(localName = "LawyeeCenterUpdateDocStatus", targetNamespace = "http://tempuri.org/", className = "com.cxf.client.LawyeeCenterUpdateDocStatus")
    @ResponseWrapper(localName = "LawyeeCenterUpdateDocStatusResponse", targetNamespace = "http://tempuri.org/", className = "com.cxf.client.LawyeeCenterUpdateDocStatusResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String lawyeeCenterUpdateDocStatus(

        @WebParam(name = "docid", targetNamespace = "http://tempuri.org/")
        java.lang.String docid
    );

    @WebMethod(operationName = "GetXMLByText", action = "http://tempuri.org/CheckFileCallBack")
    @RequestWrapper(localName = "GetXMLByText", targetNamespace = "http://tempuri.org/", className = "com.cxf.client.GetXMLByText")
    @ResponseWrapper(localName = "GetXMLByTextResponse", targetNamespace = "http://tempuri.org/", className = "com.cxf.client.GetXMLByTextResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getXMLByText(
            @WebParam(name = "DocumentData", targetNamespace = "http://tempuri.org/")
            byte[] documentData,
            @WebParam(name = "Token", targetNamespace = "http://tempuri.org/")
            java.lang.String token,
            @WebParam(name = "Sign", targetNamespace = "http://tempuri.org/")
            java.lang.String sign,
            @WebParam(name = "CaseID", targetNamespace = "http://tempuri.org/")
            java.lang.String caseID,
            //TODO 添加参数
            @WebParam(name = "OtherParaInfo", targetNamespace = "http://tempuri.org/")
            java.lang.String otherParaInfo
    );

    @WebMethod(operationName = "ImportDataExtend")
    @RequestWrapper(localName = "ImportDataExtend", targetNamespace = "http://tempuri.org/", className = "com.cxf.client.ImportDataExtend")
    @ResponseWrapper(localName = "ImportDataExtendResponse", targetNamespace = "http://tempuri.org/", className = "com.cxf.client.ImportDataExtendResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String importDataExtend(

        @WebParam(name = "key", targetNamespace = "http://tempuri.org/")
        java.lang.String key,
        @WebParam(name = "data", targetNamespace = "http://tempuri.org/")
        byte[] data,
        @WebParam(name = "xmldata", targetNamespace = "http://tempuri.org/")
        java.lang.String xmldata,
        @WebParam(name = "userID", targetNamespace = "http://tempuri.org/")
        java.lang.String userID,
        @WebParam(name = "userName", targetNamespace = "http://tempuri.org/")
        java.lang.String userName,
        @WebParam(name = "transactID", targetNamespace = "http://tempuri.org/")
        java.lang.String transactID,
        @WebParam(name = "transactName", targetNamespace = "http://tempuri.org/")
        java.lang.String transactName,
        @WebParam(name = "CourtID", targetNamespace = "http://tempuri.org/")
        java.lang.String courtID,
        @WebParam(name = "courtName", targetNamespace = "http://tempuri.org/")
        java.lang.String courtName,
        @WebParam(name = "transactDept", targetNamespace = "http://tempuri.org/")
        java.lang.String transactDept,
        @WebParam(name = "transactDeptName", targetNamespace = "http://tempuri.org/")
        java.lang.String transactDeptName,
        @WebParam(name = "effectTime", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar effectTime
    );

    @WebMethod(operationName = "UpdateDocDataStatus")
    @RequestWrapper(localName = "UpdateDocDataStatus", targetNamespace = "http://tempuri.org/", className = "com.cxf.client.UpdateDocDataStatus")
    @ResponseWrapper(localName = "UpdateDocDataStatusResponse", targetNamespace = "http://tempuri.org/", className = "com.cxf.client.UpdateDocDataStatusResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean updateDocDataStatus(

        @WebParam(name = "caseid", targetNamespace = "http://tempuri.org/")
        java.lang.String caseid,
        @WebParam(name = "dataStatus", targetNamespace = "http://tempuri.org/")
        java.lang.String dataStatus,
        @WebParam(name = "strReturnReason", targetNamespace = "http://tempuri.org/")
        java.lang.String strReturnReason
    );

    @WebMethod(operationName = "CheckFileCallBackExtend", action = "http://tempuri.org/CheckFileCallBackHY")
    @RequestWrapper(localName = "CheckFileCallBackExtend", targetNamespace = "http://tempuri.org/", className = "com.cxf.client.CheckFileCallBackExtend")
    @ResponseWrapper(localName = "CheckFileCallBackExtendResponse", targetNamespace = "http://tempuri.org/", className = "com.cxf.client.CheckFileCallBackExtendResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String checkFileCallBackExtend(

        @WebParam(name = "CaseID", targetNamespace = "http://tempuri.org/")
        java.lang.String caseID,
        @WebParam(name = "DocumentData", targetNamespace = "http://tempuri.org/")
        byte[] documentData,
        @WebParam(name = "Sign", targetNamespace = "http://tempuri.org/")
        java.lang.String sign,
        @WebParam(name = "callBackService", targetNamespace = "http://tempuri.org/")
        java.lang.String callBackService,
        @WebParam(name = "ClassName", targetNamespace = "http://tempuri.org/")
        java.lang.String className,
        @WebParam(name = "OtherParaInfo", targetNamespace = "http://tempuri.org/")
        java.lang.String otherParaInfo,
        @WebParam(name = "Token", targetNamespace = "http://tempuri.org/")
        java.lang.String token
    );

    @WebMethod(operationName = "ImportData")
    @RequestWrapper(localName = "ImportData", targetNamespace = "http://tempuri.org/", className = "com.cxf.client.ImportData")
    @ResponseWrapper(localName = "ImportDataResponse", targetNamespace = "http://tempuri.org/", className = "com.cxf.client.ImportDataResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String importData(

        @WebParam(name = "key", targetNamespace = "http://tempuri.org/")
        java.lang.String key,
        @WebParam(name = "data", targetNamespace = "http://tempuri.org/")
        byte[] data,
        @WebParam(name = "xmldata", targetNamespace = "http://tempuri.org/")
        java.lang.String xmldata,
        @WebParam(name = "userID", targetNamespace = "http://tempuri.org/")
        java.lang.String userID,
        @WebParam(name = "CourtID", targetNamespace = "http://tempuri.org/")
        java.lang.String courtID
    );

    @WebMethod(operationName = "CheckFileCallBackToken", action = "http://tempuri.org/CheckFileCallBackToken")
    @RequestWrapper(localName = "CheckFileCallBackToken", targetNamespace = "http://tempuri.org/", className = "com.cxf.client.CheckFileCallBackToken")
    @ResponseWrapper(localName = "CheckFileCallBackTokenResponse", targetNamespace = "http://tempuri.org/", className = "com.cxf.client.CheckFileCallBackTokenResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String checkFileCallBackToken(

        @WebParam(name = "CaseID", targetNamespace = "http://tempuri.org/")
        java.lang.String caseID,
        @WebParam(name = "DocumentData", targetNamespace = "http://tempuri.org/")
        byte[] documentData,
        @WebParam(name = "Sign", targetNamespace = "http://tempuri.org/")
        java.lang.String sign,
        @WebParam(name = "callBackService", targetNamespace = "http://tempuri.org/")
        java.lang.String callBackService,
        @WebParam(name = "ClassName", targetNamespace = "http://tempuri.org/")
        java.lang.String className,
        @WebParam(name = "Token", targetNamespace = "http://tempuri.org/")
        java.lang.String token
    );

    @WebMethod(operationName = "CheckFileCallBack", action = "http://tempuri.org/CheckFileCallBack")
    @RequestWrapper(localName = "CheckFileCallBack", targetNamespace = "http://tempuri.org/", className = "com.cxf.client.CheckFileCallBack")
    @ResponseWrapper(localName = "CheckFileCallBackResponse", targetNamespace = "http://tempuri.org/", className = "com.cxf.client.CheckFileCallBackResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String checkFileCallBack(

        @WebParam(name = "CaseID", targetNamespace = "http://tempuri.org/")
        java.lang.String caseID,
        @WebParam(name = "DocumentData", targetNamespace = "http://tempuri.org/")
        byte[] documentData,
        @WebParam(name = "Sign", targetNamespace = "http://tempuri.org/")
        java.lang.String sign,
        @WebParam(name = "callBackService", targetNamespace = "http://tempuri.org/")
        java.lang.String callBackService,
        @WebParam(name = "ClassName", targetNamespace = "http://tempuri.org/")
        java.lang.String className,
        @WebParam(name = "Token", targetNamespace = "http://tempuri.org/")
        java.lang.String token
    );

    @WebMethod
    @RequestWrapper(localName = "saveInterfaceLog", targetNamespace = "http://tempuri.org/", className = "com.cxf.client.SaveInterfaceLog")
    @ResponseWrapper(localName = "saveInterfaceLogResponse", targetNamespace = "http://tempuri.org/", className = "com.cxf.client.SaveInterfaceLogResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String saveInterfaceLog(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        boolean arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        SaveInterfaceLog.Arg5 arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        SaveInterfaceLog.Arg6 arg6
    );

    @WebMethod(operationName = "CheckFileCallBackHY", action = "http://tempuri.org/CheckFileCallBackHY")
    @RequestWrapper(localName = "CheckFileCallBackHY", targetNamespace = "http://tempuri.org/", className = "com.cxf.client.CheckFileCallBackHY")
    @ResponseWrapper(localName = "CheckFileCallBackHYResponse", targetNamespace = "http://tempuri.org/", className = "com.cxf.client.CheckFileCallBackHYResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String checkFileCallBackHY(

        @WebParam(name = "CaseID", targetNamespace = "http://tempuri.org/")
        java.lang.String caseID,
        @WebParam(name = "DocumentData", targetNamespace = "http://tempuri.org/")
        byte[] documentData,
        @WebParam(name = "Sign", targetNamespace = "http://tempuri.org/")
        java.lang.String sign,
        @WebParam(name = "callBackService", targetNamespace = "http://tempuri.org/")
        java.lang.String callBackService,
        @WebParam(name = "ClassName", targetNamespace = "http://tempuri.org/")
        java.lang.String className,
        @WebParam(name = "OtherParaInfo", targetNamespace = "http://tempuri.org/")
        java.lang.String otherParaInfo,
        @WebParam(name = "Token", targetNamespace = "http://tempuri.org/")
        java.lang.String token
    );

    @WebMethod
    @RequestWrapper(localName = "checkParaIsNull", targetNamespace = "http://tempuri.org/", className = "com.cxf.client.CheckParaIsNull")
    @ResponseWrapper(localName = "checkParaIsNullResponse", targetNamespace = "http://tempuri.org/", className = "com.cxf.client.CheckParaIsNullResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String checkParaIsNull(

        @WebParam(name = "arg0", targetNamespace = "")
        CheckParaIsNull.Arg0 arg0
    );

    @WebMethod(operationName = "GetDocStatus")
    @RequestWrapper(localName = "GetDocStatus", targetNamespace = "http://tempuri.org/", className = "com.cxf.client.GetDocStatus")
    @ResponseWrapper(localName = "GetDocStatusResponse", targetNamespace = "http://tempuri.org/", className = "com.cxf.client.GetDocStatusResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getDocStatus(

        @WebParam(name = "key", targetNamespace = "http://tempuri.org/")
        java.lang.String key
    );

    @WebMethod
    @RequestWrapper(localName = "getReqUrl", targetNamespace = "http://tempuri.org/", className = "com.cxf.client.GetReqUrl")
    @ResponseWrapper(localName = "getReqUrlResponse", targetNamespace = "http://tempuri.org/", className = "com.cxf.client.GetReqUrlResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getReqUrl(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getRequestIP", targetNamespace = "http://tempuri.org/", className = "com.cxf.client.GetRequestIP")
    @ResponseWrapper(localName = "getRequestIPResponse", targetNamespace = "http://tempuri.org/", className = "com.cxf.client.GetRequestIPResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getRequestIP()
;
}
